version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: cpy
    versions:
    - 8.1.1
